### ISSUE TITLE
Choosing which architecture to compile

### ISSUE THREAD

**Issue by jupmorenor** [sriharshachilakapati/AndroidOpenAL#1]
Hi, I'm trying to compile openal for android, but I don't need ALL architectures and some of them have deprecation issues that makes the compilation process to fail.
For example, armeabi shared library fails with some assembler code.
There are also issues with NEON for x86_64.

So, I want to ask you how can I choose architecture to compile only those I want?

**Comment by sriharshachilakapati** [comment]
Support for armeabi was removed in NDK r17. Which ABIs to select depends on the devices you want to target. Also, you might need to update the C source files with latest OpenAL soft source code.

How did you arrive at the conclusion that you don't need ALL architectures?

**Comment by jupmorenor** [comment]
Because I already have libopenal.so for previous architectures but no for 64bits
I'm trying to upgrade a legacy software.

I managed to get it to compile for all, using some additional flags and adding a neon2sse.h file.
But each time it has to compile every lib for each arch making a waste of time once and once again, that's why I'm asking.
